blog/urls.py
from django.urls import path
from blog.views import *

app_name = 'blog'

urlpatterns = [
    path('post/<int:pid>/',single_view,name='single'),
    path('type/<str:type>/',index_view,name='type'),
    path('category/<str:cat_name>/',index_view,name='category'),
    path('tag/<str:tag_name>/',index_view,name='tag'),
    path('author/<str:author_username>/',index_view,name='author'),
    path('search/',index_view,name='search'),
    path('post/<int:pid>/<int:cid>/',single_view,name='reply'),
]

philosophy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('website.urls')),
    path('blog/',include('blog.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('captcha/', include('captcha.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from taggit.managers import TaggableManager
from django.contrib.auth.models import User

class Type(models.Model):
    type = models.CharField(max_length=255)

    def __str__(self):
        return self.type

class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name
    
class Post(models.Model):
    title = models.CharField(max_length=255)
    type = models.ForeignKey(Type,on_delete=models.CASCADE)
    content = models.TextField()
    image = models.ImageField(upload_to='blog/',null=True,blank=True)
    video = models.FileField(upload_to='blog/video/',null=True,blank=True)
    # audio = models.FileField(upload_to='blog/audio/',null=True,blank=True)
    category = models.ManyToManyField(Category)
    author = models.ForeignKey(User,on_delete=models.SET_NULL,null=True)
    published_date = models.DateTimeField(null=True)
    views = models.BigIntegerField(default=0)
    tag = TaggableManager()
    status = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    # class Meta:
    #     ordering = ['-published_date']

    def __str__(self):
        return f"{self.title} - {self.id}"
    
class Gallery(models.Model):
    post = models.ForeignKey(Post,related_name='gallery',on_delete=models.CASCADE)
    image = models.ImageField(upload_to='blog/')

    def __str__(self):
        return self.post.title

class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE)
    name = models.ForeignKey(User,on_delete=models.SET_NULL,null=True)
    email = models.EmailField()
    subject = models.CharField(max_length=255,null=True,blank=True)
    message = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    approved = models.BooleanField(default=False)
    parent = models.ForeignKey('self',on_delete=models.CASCADE,null=True,blank=True)

    class Meta:
        ordering = ['-created_date']

    def __str__(self):
        return f"{self.id}"

blog/forms.py
from django import forms
from blog.models import Comment

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['parent','post','name','email','subject','message']

blog/views.py
from django.shortcuts import render, redirect
from blog.models import Post,Gallery, Comment
from django.utils import timezone
from django.shortcuts import get_object_or_404
from django.core.paginator import Paginator,PageNotAnInteger,EmptyPage
from blog.forms import CommentForm
from django.contrib import messages


def single_view(request,**kwargs):
    posts = Post.objects.filter(status = 1, published_date__lte = timezone.now())
    post = get_object_or_404(posts,id=kwargs['pid'])
    gallerys = Gallery.objects.filter(post=post)
    comments = Comment.objects.filter(post=kwargs['pid'], approved=True)
    if kwargs.get('cid'):
        parent = kwargs['cid']
    else: 
        parent = None
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request,messages.SUCCESS,'success')
        else:
            for errors in form.errors.values():
                for error in errors:
                    messages.add_message(request,messages.ERROR,f'{error}')
        return redirect('blog:single',pid=post.id)
    else:
        form = CommentForm()
    context = {
        'post' : post,
        'gallerys' : gallerys,
        'comments': comments,
        'form':form,
        'parent': parent,
    }
    return render(request,'blog/single.html',context)

def index_view(request,**kwargs):
    posts = Post.objects.filter(status = 1, published_date__lte = timezone.now()).order_by('-published_date')
    gallerys = Gallery.objects.all()
    if kwargs.get('type'):
        posts = posts.filter(type__type = kwargs['type'])
    if kwargs.get('cat_name'):
        posts = posts.filter(category__name = kwargs['cat_name'])
    if kwargs.get('tag_name'):
        posts = posts.filter(tag__name__in = [kwargs['tag_name']])
    if kwargs.get('author_username'):
        posts = posts.filter(author__username = kwargs['author_username'])
    if request.method == 'GET':
        if q := request.GET.get('q'):
            posts = posts.filter(content__contains = q)
    posts = Paginator(posts,4)
    try:
        page_number = request.GET.get('page')
        posts = posts.get_page(page_number)
    except PageNotAnInteger:
        posts = posts.get_page(1)
    except EmptyPage:
        posts = posts.page(posts.num_pages)
    context = {
        'posts' : posts,
        'gallerys' : gallerys,
    }
    return render(request,'blog/blog-home.html',context)

templates/blog/blog-home.html
{% extends 'base.html' %}
{% block content %}
</div> <!-- end s-pageheader -->
{% include 'blog/home.html' %}
{% endblock %}

templates/blog/category.html
<ul class="sub-menu">
    {% for cat in cats %}
    <li><a href="{% url 'blog:category' cat_name=cat %}">{{cat}}</a></li>
    {% endfor %}
</ul>

templates/blog/home.html
{% load static %}
{% load blog_tags %}
{% load humanize %}
<!-- s-content
    ================================================== -->
<section class="s-content">

    <div class="row masonry-wrap">
        <div class="masonry">

            <div class="grid-sizer"></div>
            {% for post in posts %}
            {% if post.type.type == "Standard" %}
            <article class="masonry__brick entry format-standard" data-aos="fade-up">

                <div class="entry__thumb">
                    <a href="{% url 'blog:single' pid=post.id %}" class="entry__thumb-link">
                        <img src="{{post.image.url}}" srcset="{{post.image.url}} 1x, {{post.image.url}} 2x" alt="">
                    </a>
                </div>

                <div class="entry__text">
                    <div class="entry__header">

                        <div class="entry__date">
                            <a href="single-standard.html">{{post.published_date|date:"D d/M/y"}}</a>
                        </div>
                        <h1 class="entry__title"><a href="{% url 'blog:single' pid=post.id %}">{{post.title}}</a></h1>
                        <div class="entry__date">
                            {% counted_views pid=post.id as views %}
                            <a>{{views|intword}} views</a>
                        </div>
                    </div>
                    <div class="entry__excerpt">
                        <p>
                            {{post.content|truncatewords:30|safe}}
                        </p>
                    </div>
                    <div class="entry__meta">
                        <span class="entry__meta-links">
                            {% for cat in post.category.all %}
                            <a href="{% url 'blog:category' cat_name=cat %}">{{cat}}</a>
                            {% endfor %}
                        </span>
                    </div>
                </div>

            </article> <!-- end article -->
            {% elif post.type.type == "Video" %}
            <article class="masonry__brick entry format-video" data-aos="fade-up">

                <div class="entry__thumb video-image">
                    <a href="{% url 'blog:single' pid=post.id %}" class="entry__thumb-link">
                        <video controls>
                            <source src="{{post.video.url}}">
                        </video>
                        <!-- <img src="{% static 'images/thumbs/masonry/shutterbug-400.jpg' %}"
                            srcset="{% static 'images/thumbs/masonry/shutterbug-400.jpg' %} 1x, {% static 'images/thumbs/masonry/shutterbug-800.jpg' %} 2x"
                            alt=""> -->
                    </a>
                </div>

                <div class="entry__text">
                    <div class="entry__header">

                        <div class="entry__date">
                            <a href="single-video.html">{{post.published_date|date:"D d/M/y"}}</a>
                        </div>
                        <h1 class="entry__title"><a href="{% url 'blog:single' pid=post.id %}">{{post.title}}</a>
                        </h1>
                        <div class="entry__date">
                            {% counted_views pid=post.id as views %}
                            <a>{{views|intword}} views</a>
                        </div>
                    </div>
                    <div class="entry__excerpt">
                        <p>
                            {{post.content|truncatewords:30|safe}}
                        </p>
                    </div>
                    <div class="entry__meta">
                        <span class="entry__meta-links">
                            {% for cat in post.category.all %}
                            <a href="{% url 'blog:category' cat_name=cat %}">{{cat}}</a>
                            {% endfor %}
                        </span>
                    </div>
                </div>

            </article> <!-- end article -->
            {% elif post.type.type == "Gallery" %}
            <article class="masonry__brick entry format-gallery" data-aos="fade-up">

                <div class="entry__thumb slider">
                    <div class="slider__slides">
                        {% for gallery in gallerys %}
                        {% if gallery.post.id == post.id %}
                        <div class="slider__slide">
                            <img src="{{gallery.image.url}}" srcset="{{gallery.image.url}} 1x, {{gallery.image.url}} 2x"
                                alt="">
                        </div>
                        {% endif %}
                        {% endfor %}
                    </div>
                </div>

                <div class="entry__text">
                    <div class="entry__header">

                        <div class="entry__date">
                            <a href="single-gallery.html">{{post.published_date|date:"D d/M/y"}}</a>
                        </div>
                        <h1 class="entry__title"><a href="{% url 'blog:single' pid=post.id %}">{{post.title}}</a>
                        </h1>
                        <div class="entry__date">
                            {% counted_views pid=post.id as views %}
                            <a>{{views|intword}} views</a>
                        </div>
                    </div>
                    <div class="entry__excerpt">
                        <p>
                            {{post.content|truncatewords:30|safe}}
                        </p>
                    </div>
                    <div class="entry__meta">
                        <span class="entry__meta-links">
                            {% for cat in post.category.all %}
                            <a href="{% url 'blog:category' cat_name=cat %}">{{cat}}</a>
                            {% endfor %}
                        </span>
                    </div>
                </div>

            </article> <!-- end article -->
            {% endif %}
            {% endfor %}

        </div> <!-- end masonry -->
    </div> <!-- end masonry-wrap -->

    <div class="row">
        <div class="col-full">
            <nav class="pgn">
                <ul>
                    {% if posts.has_previous %}
                    <li><a class="pgn__prev" href="?page={{posts.previuos_page_number}}">Prev</a></li>
                    {% endif %}
                    {% for i in posts.paginator.page_range %}
                    {% if posts.number == i %}
                    <li><a class="pgn__num current" href="?page={{i}}">{{i}}</a></li>
                    {% else %}
                    <li><a class="pgn__num" href="?page={{i}}">{{i}}</a></li>
                    {% endif %}
                    {% endfor %}
                    {% if posts.has_next %}
                    <li><a class="pgn__next" href="?page={{posts.next_page_number}}">Next</a></li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>

</section> <!-- s-content -->

templates/blog/lastest-post.html
{% load static %}
<div class="featured">
    {% for post in posts %}
    {% if forloop.first %}
    <div class="featured__column featured__column--big">
        {% if post.type.type == "Standard" %}
        <div class="entry" style="background-image:url('{{post.image.url}}');">
            {% elif post.type.type == "Video" %}
            <div class="entry">
                <video autoplay muted loop id="bg-video">
                    <source src="{{post.video.url}}" type="video/mp4">
                </video>
                {% elif post.type.type == "Gallery" %}
                <div class="entry" style="background-image:url('{{post.image.url}}');">
                    {% endif %}
                    <div class="entry__content">
                        {% for cat in post.category.all %}
                        <span class="entry__category"><a
                                href="{% url 'blog:category' cat_name=cat %}">{{cat}}</a></span>
                        {% endfor %}
                        <h1><a href="{% url 'blog:single' pid=post.id %}" title="">{{post.title}}</a>
                        </h1>

                        <div class="entry__info">
                            <a href="#0" class="entry__profile-pic">
                                <img class="avatar" src="{% static 'images/unknown.jpg' %}" alt="">
                            </a>

                            <ul class="entry__meta">
                                <li><a
                                        href="{% url 'blog:author' author_username=post.author %}">{{post.author.get_full_name}}</a>
                                </li>
                                <li>{{post.published_date|date:"D d/M/y"}}</li>
                            </ul>
                        </div>
                    </div> <!-- end entry__content -->

                </div> <!-- end entry -->
            </div> <!-- end featured__big -->
            {% else %}
            <div class="featured__column featured__column--small">
                {% if post.type.type == "Standard" %}
                <div class="entry" style="background-image:url('{{post.image.url}}');">
                    {% elif post.type.type == "Video" %}
                    <div class="entry">
                        <video autoplay muted loop id="bg-video">
                            <source src="{{post.video.url}}" type="video/mp4">
                        </video>
                        {% elif post.type.type == "Gallery" %}
                        <div class="entry" style="background-image:url('{{post.image.url}}');">
                            {% endif %}
                            <div class="entry__content">
                                {% for cat in post.category.all %}
                                <span class="entry__category"><a
                                        href="{% url 'blog:category' cat_name=cat %}">{{cat}}</a></span>
                                {% endfor %}
                                <h1><a href="{% url 'blog:single' pid=post.id %}" title="">{{post.title}}</a></h1>

                                <div class="entry__info">

                                    <ul class="entry__meta">
                                        <li><a
                                                href="{% url 'blog:author' author_username=post.author %}">{{post.author.get_full_name}}</a>
                                        </li>
                                        <li>{{post.published_date|date:"D d/M/y"}}</li>
                                    </ul>
                                </div>
                            </div> <!-- end entry__content -->

                        </div> <!-- end entry -->

                    </div> <!-- end featured__small -->
                    {% endif %}
                    {% endfor %}
                </div> <!-- end featured -->

templates/blog/popular-posts.html
{% load static %}
{% load blog_tags %}
<div class="col-eight md-six tab-full popular">
    <h3>Popular Posts</h3>

    <div class="block-1-2 block-m-full popular__posts">
        {% for post in posts %}
        <article class="col-block popular__post">
            <a href="{% url 'blog:single' pid=post.id %}" class="popular__thumb">
                {% if post.type.type == "Standard" %}
                <img src="{{post.image.url}}" alt="">
                {% elif post.type.type == "Video" %}
                <video src="{{post.video.url}}" alt="" style="width: 20%;">
                {% elif post.type.type == "Gallery" %}
                <img src="{{post.image.url}}" alt="">
                {% endif %}
            </a>
            <h5><a href="{% url 'blog:single' pid=post.id %}">{{post.title}}</a></h5>
            <section class="popular__meta">
                <span class="popular__author"><span>By</span> <a href="{% url 'blog:author' author_username=post.author %}">{{post.author.get_full_name}}</a></span>
                <span class="popular__date"><span>on</span> <time datetime="2017-12-19">{% time pid=post.id %}</time></span>
            </section>
        </article>
        {% endfor %}
    </div> <!-- end popular_posts -->
</div> <!-- end popular -->

templates/blog/show-reply.html
{% load static %}
{% load blog_tags %}

<ul class="children">
    {% for comment in comments %}
    <li class="depth-2 comment">

        <div class="comment__avatar">
            <img width="50" height="50" class="avatar" src="{% static 'images/unknown.jpg' %}" alt="">
        </div>

        <div class="comment__content">

            <div class="comment__info">
                <cite>{{comment.name.get_full_name}}</cite>

                <div class="comment__meta">
                    <time class="comment__time">{% timecomment pid=comment.id %}</time>
                    <a class="reply" href="{% url 'blog:reply' pid=post.id cid=comment.id %}#entercomment">Reply</a>
                </div>
            </div>

            <div class="comment__text">
                <p>{{reply}}{{comment.message}}</p>
            </div>

        </div>

       {% show_reply1 pid=post.id cid=comment.id %}

    </li>
    {% endfor %}

</ul>

templates/blog/single.html
{% extends 'base.html' %}
{% load static %}
{% load blog_tags %}
{% block content %}
{% load humanize %}
</div> <!-- end s-pageheader -->


<!-- s-content
    ================================================== -->
<section class="s-content s-content--narrow s-content--no-padding-bottom">

    <article class="row format-standard">

        <div class="s-content__header col-full">
            <h1 class="s-content__header-title">
                {{post.title}}
            </h1>
            <ul class="s-content__header-meta">
                <li class="date">{{post.published_date|date:"D d/M/y"}}</li>
                <li class="cat">
                    In
                    {% for cat in post.category.all %}
                    <a href="{% url 'blog:category' cat_name=cat %}">{{cat}}</a>
                    {% endfor %}
                </li>
                {% counted_views pid=post.id as views %}
                <li class="view">{{views|intword}} views</li>
            </ul>
        </div> <!-- end s-content__header -->

        <div class="s-content__media col-full">
            {% if post.type.type == "Standard" %}
            <div class="s-content__post-thumb" style="margin-left: 120px;">
                <img src="{{post.image.url}}" srcset="{{post.image.url}} 2000w,
                                 {{post.image.url}} 1000w,
                                 {{post.image.url}} 500w" sizes="(max-width: 2000px) 100vw, 2000px" alt="">
            </div>
            {% elif post.type.type == "Video" %}
            <div class="video-container">
                <video controls>
                    <source src="{{post.video.url}}">
                </video>
            </div>
            {% elif post.type.type == "Gallery" %}
            <div class="s-content__slider slider" style="margin-left: 80px;">
                <div class="slider__slides">
                    {% for gallery in gallerys %}
                    <div class="slider__slide">
                        <img src="{{gallery.image.url}}" srcset="{{gallery.image.url}} 2000w,
                                         {{gallery.image.url}} 1000w,
                                         {{gallery.image.url}} 500w" sizes="(max-width: 2000px) 100vw, 2000px" alt="">
                    </div>
                    {% endfor %}
                </div>
            </div>
            {% endif %}
        </div> <!-- end s-content__media -->

        <div class="col-full s-content__main">

            <p class="lead">{{post.content|safe}}</p>

            <p class="s-content__tags">
                <span>Post Tags</span>

                <span class="s-content__tag-list">
                    {% for tag in post.tag.all %}
                    <a href="{% url 'blog:tag' tag_name=tag %}">{{tag}}</a>
                    {% endfor %}
                </span>
            </p> <!-- end s-content__tags -->

            <div class="s-content__author">

                <div class="s-content__author-about">
                    <h4 class="s-content__author-name">
                        <a href="{% url 'blog:author' author_username=post.author %}">{{post.author.get_full_name}}</a>
                    </h4>

                    <p>Alias aperiam at debitis deserunt dignissimos dolorem doloribus, fuga fugiat impedit
                        laudantium magni maxime nihil nisi quidem quisquam sed ullam voluptas voluptatum. Lorem
                        ipsum dolor sit amet, consectetur adipisicing elit.
                    </p>

                    <ul class="s-content__author-social">
                        <li><a href="#0">Facebook</a></li>
                        <li><a href="#0">Twitter</a></li>
                        <li><a href="#0">GooglePlus</a></li>
                        <li><a href="#0">Instagram</a></li>
                    </ul>
                </div>
            </div>

            {% show_prev_next pid=post.id %}

        </div> <!-- end s-content__main -->

    </article>


    <!-- comments
        ================================================== -->
    <div class="comments-wrap">

        <div id="comments" class="row">
            <div class="col-full">

                <h3 class="h2">{{comments|length}} Comments</h3>

                <!-- commentlist -->
                <ol class="commentlist">

                    <!-- <li class="depth-1 comment">

                        <div class="comment__avatar">
                            <img width="50" height="50" class="avatar" src="{% static 'images/avatars/user-01.jpg' %}"
                                alt="">
                        </div>

                        <div class="comment__content">

                            <div class="comment__info">
                                <cite>Itachi Uchiha</cite>

                                <div class="comment__meta">
                                    <time class="comment__time">Dec 16, 2017 @ 23:05</time>
                                    <a class="reply" href="#0">Reply</a>
                                </div>
                            </div>

                            <div class="comment__text">
                                <p>Adhuc quaerendum est ne, vis ut harum tantas noluisse, id suas iisque mei. Nec te
                                    inani ponderum vulputate,
                                    facilisi expetenda has et. Iudico dictas scriptorem an vim, ei alia mentitum est, ne
                                    has voluptua praesent.</p>
                            </div>

                        </div>

                    </li> end comment level 1 -->
                    {% for comment in comments %}
                    {% if not comment.parent %}
                    <li class="thread-alt depth-1 comment">

                        <div class="comment__avatar">
                            <img width="50" height="50" class="avatar" src="{% static 'images/unknown.jpg' %}" alt="">
                        </div>

                        <div class="comment__content">

                            <div class="comment__info">
                                <cite>{{comment.name.get_full_name}}</cite>

                                <div class="comment__meta">
                                    <time class="comment__time">{% timecomment pid=comment.id %}</time>
                                    <a class="reply"
                                        href="{% url 'blog:reply' pid=post.id cid=comment.id %}#entercomment">Reply</a>
                                </div>
                            </div>

                            <div class="comment__text">
                                <p>{{comment.message}}</p>
                            </div>

                        </div>

                        {% show_reply pid=post.id cid=comment.id %}
                    </li> <!-- end comment level 1 -->
                    {% endif %}
                    {% endfor %}
                    <!-- <li class="depth-1 comment">

                        <div class="comment__avatar">
                            <img width="50" height="50" class="avatar" src="{% static 'images/avatars/user-02.jpg' %}"
                                alt="">
                        </div>

                        <div class="comment__content">

                            <div class="comment__info">
                                <cite>Shikamaru Nara</cite>

                                <div class="comment__meta">
                                    <time class="comment-time">Dec 16, 2017 @ 25:15</time>
                                    <a class="reply" href="#">Reply</a>
                                </div>
                            </div>

                            <div class="comment__text">
                                <p>Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum
                                    claritatem.</p>
                            </div>

                        </div>

                    </li> end comment level 1 -->

                </ol> <!-- end commentlist -->


                <!-- respond
                    ================================================== -->
                <div class="respond" id="entercomment">

                    <h3 class="h2">Add Comment</h3>
                    {% if parent %}
                    <form name="contactForm" id="contactForm" method="post"
                        action="{% url 'blog:single' pid=post.id %}">
                        {% csrf_token %}
                        <fieldset>
                            <div class="form-field">
                                <input type="hidden" name="parent" value='{{parent}}'>
                            </div>
                            <div class="form-field">
                                <input type="hidden" name="post" value={{post.id}}>
                            </div>
                            <div class="form-field">
                                <input name="name" type="hidden" id="cName" class="full-width" placeholder="Your Name"
                                    value="{{request.user.id}}">
                            </div>

                            <div class="form-field">
                                <input name="email" type="hidden" id="cEmail" class="full-width"
                                    placeholder="Your Email" value="{{request.user.email}}">
                            </div>

                            <div class="form-field">
                                <input name="subject" type="text" id="cWebsite" class="full-width" placeholder="Subject"
                                    value="">
                            </div>

                            <div class="message form-field">
                                <textarea name="message" id="cMessage" class="full-width"
                                    placeholder="Your Message"></textarea>
                            </div>

                            <button type="submit" class="submit btn--primary btn--large full-width">Submit</button>

                        </fieldset>
                    </form> <!-- end form -->
                    {% else %}
                    <form name="contactForm" id="contactForm" method="post"
                        action="{% url 'blog:single' pid=post.id %}">
                        {% csrf_token %}
                        <fieldset>
                            <div class="form-field">
                                <input type="hidden" name="parent" value=''>
                            </div>
                            <div class="form-field">
                                <input type="hidden" name="post" value={{post.id}}>
                            </div>
                            <div class="form-field">
                                <input name="name" type="hidden" id="cName" class="full-width" placeholder="Your Name"
                                    value="{{request.user.id}}">
                            </div>

                            <div class="form-field">
                                <input name="email" type="hidden" id="cEmail" class="full-width"
                                    placeholder="Your Email" value="{{request.user.email}}">
                            </div>

                            <div class="form-field">
                                <input name="subject" type="text" id="cWebsite" class="full-width" placeholder="Subject"
                                    value="">
                            </div>

                            <div class="message form-field">
                                <textarea name="message" id="cMessage" class="full-width"
                                    placeholder="Your Message"></textarea>
                            </div>

                            <button type="submit" class="submit btn--primary btn--large full-width">Submit</button>

                        </fieldset>
                    </form> <!-- end form -->
                    {% endif %}

                </div> <!-- end respond -->

            </div> <!-- end col-full -->

        </div> <!-- end row comments -->
    </div> <!-- end comments-wrap -->

</section> <!-- s-content -->
{% endblock %}