blog/urls.py
from django.urls import path
from blog.views import *

app_name = 'blog'

urlpatterns = [
    path('post/<int:pid>/',single_view,name='single'),
    path('type/<str:type>/',index_view,name='type'),
    path('category/<str:cat_name>/',index_view,name='category'),
    path('tag/<str:tag_name>/',index_view,name='tag'),
    path('author/<str:author_username>/',index_view,name='author'),
    path('search/',index_view,name='search'),
    path('post/<int:pid>/<int:cid>/',single_view,name='reply'),
]

philosophy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('website.urls')),
    path('blog/',include('blog.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('captcha/', include('captcha.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from website.views import *

app_name = 'website'

urlpatterns = [
    path('',index_view,name='index'),
    path('about/',about_view,name='about'),
    path('contact/',contact_view,name='contact'),
    path('newsletter/',newsletter_view,name='newsletter'),
]

templates/base.html
{% load static %}
{% load blog_tags %}
<!DOCTYPE html>
<html class="no-js" lang="en">

<head>

    <!--- basic page needs
    ================================================== -->
    <meta charset="utf-8">
    <title>Philosophy</title>
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- mobile specific metas
    ================================================== -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- CSS
    ================================================== -->
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/vendor.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">

    <!-- script
    ================================================== -->
    <script src="{% static 'js/modernizr.js' %}"></script>
    <script src="{% static 'js/pace.min.js' %}"></script>

    <!-- favicons
    ================================================== -->
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
			integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

</head>

<body id="top">

    <!-- pageheader
    ================================================== -->
    {% if request.resolver_match.view_name == 'website:index' %}
    <section class="s-pageheader s-pageheader--home">
    {% else %}
    <div class="s-pageheader">
    {% endif %}
        <header class="header">
            <div class="header__content row">

                <div class="header__logo">
                    <a class="logo" href="{% url 'website:index' %}">
                        <img src="{% static 'images/logo.svg' %}" alt="Homepage">
                    </a>
                </div> <!-- end header__logo -->

                <ul class="header__social">
                    <li><a href="#">Login</a></li>
                    <li><a href="#">Signup</a></li>
                </ul> <!-- end header__social -->

                <a class="header__search-trigger" href="#0"></a>

                <div class="header__search">

                    <form role="search" method="get" class="header__search-form" action="{% url 'blog:search' %}">
                        <label>
                            <span class="hide-content">Search for:</span>
                            <input type="search" class="search-field" placeholder="Type Keywords" value="" name="q"
                                title="Search for:" autocomplete="off">
                        </label>
                        <input type="submit" class="search-submit" value="Search">
                    </form>

                    <a href="#0" title="Close Search" class="header__overlay-close">Close</a>

                </div> <!-- end header__search -->


                <a class="header__toggle-menu" href="#0" title="Menu"><span>Menu</span></a>

                <nav class="header__nav-wrap">

                    <h2 class="header__nav-heading h6">Site Navigation</h2>

                    <ul class="header__nav">
                        <li class="current"><a href="{% url 'website:index' %}" title="">Home</a></li>
                        <li class="has-children">
                            <a href="#0" title="">Categories</a>
                            {% show_category %}
                        </li>
                        <li class="has-children">
                            <a href="#0" title="">Blog</a>
                            <ul class="sub-menu">
                                <li><a href="{% url 'blog:type' type='Video' %}">Video Post</a></li>
                                <li><a href="{% url 'blog:type' type='Gallery' %}">Gallery Post</a></li>
                                <li><a href="{% url 'blog:type' type='Standard' %}">Standard Post</a></li>
                            </ul>
                        </li>
                        <li><a href="{% url 'website:about' %}" title="">About</a></li>
                        <li><a href="{% url 'website:contact' %}" title="">Contact</a></li>
                    </ul> <!-- end header__nav -->

                    <a href="#0" title="Close Menu" class="header__overlay-close close-mobile-menu">Close</a>

                </nav> <!-- end header__nav-wrap -->

            </div> <!-- header-content -->
            {% include 'messages.html' %}
        </header> <!-- header -->

        {% block content %}
        {% endblock %}

        <!-- s-extra
    ================================================== -->
        <section class="s-extra">

            <div class="row top">

            {% popular_post %}

                <div class="col-four md-six tab-full about">
                    <h3>About Philosophy</h3>

                    <p>
                        Donec sollicitudin molestie malesuada. Nulla quis lorem ut libero malesuada feugiat.
                        Pellentesque in ipsum id orci porta dapibus. Vestibulum ante ipsum primis in faucibus orci
                        luctus et ultrices posuere cubilia Curae; Donec velit neque, auctor sit amet aliquam vel,
                        ullamcorper sit amet ligula. Quisque velit nisi, pretium ut lacinia in, elementum id enim. Donec
                        sollicitudin molestie malesuada.
                    </p>
                </div> <!-- end about -->

            </div> <!-- end row -->

            {% show_tags %}

        </section> <!-- end s-extra -->


        <!-- s-footer
    ================================================== -->
        <footer class="s-footer">

            <div class="s-footer__main">
                <div class="row">

                    <div class="col-two md-four mob-full s-footer__sitelinks">

                        <h4>Quick Links</h4>

                        <ul class="s-footer__linklist">
                            <li><a href="#0">Home</a></li>
                            <li><a href="#0">Blog</a></li>
                            <li><a href="#0">Styles</a></li>
                            <li><a href="#0">About</a></li>
                            <li><a href="#0">Contact</a></li>
                            <li><a href="#0">Privacy Policy</a></li>
                        </ul>

                    </div> <!-- end s-footer__sitelinks -->

                    <div class="col-two md-four mob-full s-footer__archives">

                        <h4>Archives</h4>

                        <ul class="s-footer__linklist">
                            <li><a href="#0">January 2018</a></li>
                            <li><a href="#0">December 2017</a></li>
                            <li><a href="#0">November 2017</a></li>
                            <li><a href="#0">October 2017</a></li>
                            <li><a href="#0">September 2017</a></li>
                            <li><a href="#0">August 2017</a></li>
                        </ul>

                    </div> <!-- end s-footer__archives -->

                    <div class="col-two md-four mob-full s-footer__social">

                        <h4>Social</h4>

                        <ul class="s-footer__linklist">
                            <li><a href="#0">Facebook</a></li>
                            <li><a href="#0">Instagram</a></li>
                            <li><a href="#0">Twitter</a></li>
                            <li><a href="#0">Pinterest</a></li>
                            <li><a href="#0">Google+</a></li>
                            <li><a href="#0">LinkedIn</a></li>
                        </ul>

                    </div> <!-- end s-footer__social -->

                    <div class="col-five md-full end s-footer__subscribe">

                        <h4>Our Newsletter</h4>

                        <p>Sit vel delectus amet officiis repudiandae est voluptatem. Tempora maxime provident nisi et
                            fuga et enim exercitationem ipsam. Culpa consequatur occaecati.</p>

                        <div class="subscribe-form">
                            <form class="group" novalidate="true" action="{% url 'website:newsletter' %}" method="post">
                                {% csrf_token %}
                                <input type="email" value="" name="email" class="email" id="mc-email"
                                    placeholder="Email Address" required="">

                                <input type="hidden" name="next"
											value="{{request.path}}">

                                <input type="submit" name="subscribe" value="Send">

                                <label for="mc-email" class="subscribe-message"></label>

                            </form>
                        </div>

                    </div> <!-- end s-footer__subscribe -->

                </div>
            </div> <!-- end s-footer__main -->

            <div class="s-footer__bottom">
                <div class="row">
                    <div class="col-full">
                        <div class="s-footer__copyright">
                            <span>© Copyright Philosophy 2018</span>
                            <span>Site Template by <a href="https://colorlib.com/">Colorlib</a></span>
                        </div>

                        <div class="go-top">
                            <a class="smoothscroll" title="Back to Top" href="#top"></a>
                        </div>
                    </div>
                </div>
            </div> <!-- end s-footer__bottom -->

        </footer> <!-- end s-footer -->


        <!-- preloader
    ================================================== -->
        <div id="preloader">
            <div id="loader">
                <div class="line-scale">
                    <div></div>
                    <div></div>
                    <div></div>
                    <div></div>
                    <div></div>
                </div>
            </div>
        </div>


        <!-- Java Script
    ================================================== -->
        <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
        <script src="{% static 'js/plugins.js' %}"></script>
        <script src="{% static 'js/main.js' %}"></script>
        <script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
        <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
        <script>
            window.dataLayer = window.dataLayer || [];

            function gtag() {
                dataLayer.push(arguments);
            }
            gtag('js', new Date());

            gtag('config', 'UA-23581568-13');
        </script>
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
			integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous">
		</script>
		<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
			integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
		</script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
			integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
		</script>
</body>

</html>

templates/messages.html
{% for message in messages %}
<div class="container-fluid p-0">
  <div class="alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="True">&times;</span>
    </button>
    {{ message }}
  </div>
</div>
{% endfor %}